name: Chromic Backend CI/CD Pipeline

name: Spring Boot CI/CD with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon --parallel --console=plain

      - name: Run Gradle Tests
        run: ./gradlew test

      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-jar
          path: build/libs/*.jar