


name: Chromic Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
                        ${{ runner.os }}-gradle-

      - name: Run Gradle tests
        run: ./gradlew test

  publish-image:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to container registry
        run:  docker login --username ${{vars.DH_USERNAME}} --password ${{ secrets.GH_PAT }} ghcr.io

      - name: Build image
        run: docker build . --tag ghcr.io/${{vars.GH_USERNAME}}/${{vars.IMAGE_NAME}}:latest

      - name: Publish image
        run: docker push ghcr.io/${{vars.GH_USERNAME}}/${{vars.IMAGE_NAME}}:latest

